### ISSUE TITLE
ID Vergabe - Einheitliches Format 

### ISSUE THREAD

**Issue by sheila62** [pschm/am-lastenheft-ss20#21]
Alle Aspekte des Lastenhefts benötigen eine ID. Wenns geht automatisch generiert?
Verweis von z.B. funktionalen Anforderungen auf die Quelle (Anhang: Interviewleitfäden usw.). Beachte auch mehrere Quellenverweise für eine Anf. möglich

Einheitliches Format vorgeben für alle (z.B. NF-Anforderungen und F-Anforderungen)

**Comment by RedAvenge** [comment]
Mögliche aufgekommene Ideen: Anforderung als kleine Tabelle? Oder mehrere Spiegelstriche pro Anf.
