### ISSUE TITLE
Personas aus den Interviews/Fragebögen generieren

### ISSUE THREAD

**Issue by STFJO** [pschm/am-lastenheft-ss20#24]
Am einfachsten orientiert ihr euch dabei an den N/FAs die ihr im jeweiligen Team schon aus den entsprechenden Quellen gezogen habt, zugegebenermaßen etwas falsch rum, aber macht auch keinen Sinn so zu tun als hätten wir noch keine N/FAs.

**Comment by ghost** [comment]
Sollte bei uns (Team7/8) mittlerweilse fertig sein.
