### ISSUE TITLE
Stakeholderliste ergänzen, mit ID versehen und kategorisieren

### ISSUE THREAD

**Issue by stefanbente** [pschm/am-lastenheft-ss20#27]

**Comment by stefanbente** [comment]
Tabellarisch: ID / Kategorie / Vertreter

**Comment by RedAvenge** [comment]
@faweizz du hast das letzte Label entfernt aber das Issue noch nicht geschlossen.
Gibt es hier noch was zu tun, wenn ja bitte erläutern und ein Team zuweisen. Ansonsten bitte schließen.
