### ISSUE TITLE
Personas-Liste aufstellen und mit Stakeholdern abgleichen

### ISSUE THREAD

**Issue by stefanbente** [pschm/am-lastenheft-ss20#47]
* Begründung, warum gerade *diese* Personas. 
* bitte keine "silly names", konsistente Benamung

**Comment by STFJO** [comment]
Keine Silly Names mehr vorhanden, Benennung sollte soweit OK sein.

Abgleichung mit Stakeholdern bräuchte noch Rücksprache mit Team 1 (Kategorisierung der Stakeholder sieht inkonsistent aus)

**Comment by stefanbente** [comment]
InnoHub / TH / Firmen

**Comment by StephanHagge** [comment]
Kategorien wurden angepasst
