### ISSUE TITLE
Glossareinträge alphabetisch sortieren

### ISSUE THREAD

**Issue by stefanbente** [pschm/am-lastenheft-ss20#49]

**Comment by RedAvenge** [comment]
Fertig.
IDs sind nach dem Muster, dass die erst beiden Zahlen den Buchstaben als Zahl wiederspiegelt (Also bpsw. Begriff mit `S` hat `GL-19xx` als ID. So können dazwischen weitere Begriffe eingefügt werden, ohne das die IDs alle neu gemacht werden müssen.
