### ISSUE TITLE
Tabelle Ziel => Liste von funktionalen Anforderungen

### ISSUE THREAD

**Issue by stefanbente** [pschm/am-lastenheft-ss20#58]
Team 4 organisiert das. (weist jedem Teilteam 1-2 Ziele zu, um die dazugehörigen Anforderungen zu definieren)

**Comment by stefanbente** [comment]
Team 4 macht 1 Beispiel

**Comment by soeztue** [comment]
Einteilung: 
Team-1 – ZI-0101, ZI-0102, ZI-0103
Team-2 – ZI-0104, ZI-0105, ZI-0107
Team-4 - ZI-0109, ZI-0110
Team-5 - ZI-0111, ZI-0112
Team-6 – ZI-0108, ZI-0113, ZI-0114
Team-7 – ZI-0115, ZI-0116
Team-8 – ZI-0117, ZI-0118, ZI-0119
