### ISSUE TITLE
Interviewleitfäden in Markdown formatieren und auf GitHub laden

### ISSUE THREAD

**Issue by pschm** [pschm/am-lastenheft-ss20#6]
Kleiner Hinweis zur Benennung der Dateien:
GitBook arbeitet Case-Sensitive, daher am bestern Dateinamen komplett klein belassen. Denk auch bitte daran eure Dateien in der Datei [SUMMARY.md](../blob/master/SUMMARY.md) einzutragen, damit die Verlinkungen auch auf GitBook funktionieren.

**Comment by RedAvenge** [comment]
Team 8: Done
