### ISSUE TITLE
Kapitelstruktur für Szenarien / Personas finalisieren

### ISSUE THREAD

**Issue by stefanbente** [pschm/am-lastenheft-ss20#62]

**Comment by STFJO** [comment]
Kapitelstruktur für Personas wurde finalisiert, Personas müssen teilweise noch umgeschrieben werden, wurden entsprechend vorläufig in aktueller Struktur belassen um sie für die Autoren leicht auffindbar zu erhalten.

**Comment by TillHein** [comment]
Licht aus
