### ISSUE TITLE
Priorisierung der Anforderungen über AHP, CAF&PMI

### ISSUE THREAD

**Issue by MHallweger** [pschm/am-lastenheft-ss20#68]
Informationen im Discord Kanal “6-kano-priorisierung-konfliktlösung”

**Comment by ghost** [comment]
Hallo wir (Team 7/8) wissen nicht genau, was mit einer Projekt-Infrastruktur gemeint ist. Das behindert uns bei der Priorisierungsaufgabe der Nichtfunktionalen Anforderungen. Könnte dazu ein eintrag im Glossar angelegt werden?

**Comment by stefanbente** [comment]
Lässt sich nicht klären. Rausnehmen.

**Comment by RedAvenge** [comment]
Hier die Datei von Gruppe A: [CAF_und_PMI.xlsx](https://github.com/pschm/am-lastenheft-ss20/files/4954534/CAF_und_PMI.xlsx)

Unsere Ergebnisse sind nach Punkten eher negativ ausgefallen. Ist das dennoch verwertbar oder wo können wir noch zur Verbesserung ansetzten?

**Comment by faweizz** [comment]
Freitag: Diskussionsbedarf Datenplattform -> Alerting
