### ISSUE TITLE
Umfragen in den Anhang aufnehmen

### ISSUE THREAD

**Issue by pschm** [pschm/am-lastenheft-ss20#7]
Kleiner Hinweis zur Benennung der Dateien:
GitBook arbeitet Case-Sensitive, daher am bestern Dateinamen komplett klein belassen. Denk auch bitte daran eure Dateien in der Datei [SUMMARY.md](../blob/master/SUMMARY.md) einzutragen, damit die Verlinkungen auch auf GitBook funktionieren.

**Comment by pschm** [comment]
Prof./Ma fertig.

**Comment by StephanHagge** [comment]
Unternehmen fertig
