### ISSUE TITLE
GitBook Content nach Archi-Lab migrieren, um PDF Export zu erhalten

### ISSUE THREAD

**Issue by stefanbente** [pschm/am-lastenheft-ss20#73]
Das PDF-Export-Feature scheint nur in den höheren Plänen verfügbar zu sein, nicht in "Personal". 

Alternative: Man lässt sich als nichtkommerzielle Organisation registrieren.

**Comment by pschm** [comment]
Wie verfügbar muss der PDF-Export sein? Nur einmalig, wenn das Modul abgeschlossen ist, dann würde es ausreichen, auf die 14-tägige Testversion zurückzugreifen und den Export einmalig durchzuführen.

Bzgl. der Registrierung der nicht kommerziellen Organisation. Wir können das mal versuchen durchzuführen. Dann wäre noch die Frage, sollen wir eine Organisation für dieses Semester anlegen oder macht es Sinn, wenn sie dies als Archi-Lab anstoßen?

**Comment by stefanbente** [comment]
Das mit ArchiLab als Organisation habe ich schon angestoßen, bis jetzt aber kein Resultat. Wenn das nix gibt, machen wir das mit der Testversion.

**Comment by pschm** [comment]
Gibt es hier bzgl. der Registrierung von Archi-Lab als nicht-kommerzielle Organisation weitere Erkenntnisse?

**Comment by pschm** [comment]
PDF ist erzeugt und wird heute noch per E-Mail an @stefanbente geschickt.
