### ISSUE TITLE
Glossareinträge ergänzen/pflegen

### ISSUE THREAD

**Issue by pschm** [pschm/am-lastenheft-ss20#9]
Wenn Glossareinträge innerhalb des Lastenhefts verlinkt werden sollen, achtet bitte darauf einen entsprechenden Anchor zuzuweisen. Nähere Informationen findet ihr [hier](https://github.com/pschm/am-lastenheft-ss20/blob/master/muster/quellen-verlinkung.md).

**Comment by TillHein** [comment]
Glossar Einträge sind gepflegt
