### ISSUE TITLE
Bilder in Umfrageauswertung laden in Gitbook nicht

### ISSUE THREAD

**Issue by RedAvenge** [pschm/am-lastenheft-ss20#97]
Liegt sehr wahrscheinlich daran, dass die Bilder nicht relativ verlinkt sind. Im Unterkapitel 2 funktionieren die Bilder nämlich [im Gitbook](https://philipp-schmeier.gitbook.io/am-lastenheft-ss20/lastenheft/10.-anhang/umfragen/auswertungen) und dort sind diese bereits relativ verlinkt.

In Kapitel 3 sollte zusätzlich geschaut werden, ob die Überschriften eine Ebene weiter gemacht werden sollte (also 5 statt 4 Rauten), damit diese nicht in der "Contents"-Übersicht im Gitbook oben rechts auftauchen.

**Comment by GfalahO** [comment]
Team 6 Done!
