### ISSUE TITLE
Glossarbegriffe nicht verlinkt

### ISSUE THREAD

**Issue by RedAvenge** [pschm/am-lastenheft-ss20#98]
Es gibt eine Reihe an Begriffen im Glossar, auf die nirgends im Lastenheft verwiesen wird. Wir haben im LH nachgeschaut und die Begriffe selbst gesucht und diese werden sehr häufig verwendet, sind aber eben nicht verlinkt. Im Rahmen der QS Nachbereitung ist es jetzt die Aufgabe des jeweiligen Kapitel-Teams die nicht verlinkten Begriffe zu verlinken.

Die betroffenen Glossar-IDs und deren Begriff-Vorkommnisse in den Kapiteln sind:
- GL-0100: Kapitel 2 (Hinweis: Im Glossar steht "Additive Fertigung", im LH aber nur "Additive Manufacturing". Bitte Begriff im Glossar anpassen)
- GL-0103: Kapitel 4
- GL-0104: Kapitel 4
- GL-0400: Kapitel 2, 4
- GL-0401: Kapitel 4
- GL-0403: Kapitel 4
- GL-0404: Diese ID ist doppelt vergeben! Beide Begriffe werden auch bereits in Kapitel 1 und 5 verlinkt . Klärt hier unter euch, welcher Begriff eine neue eindeutige ID bekommt und passt die entsprechenden Verlinkungen auf die neue ID an.
- GL-0900: Kapitel 4, 6 (Hinweis: Ist im LH nur als "Ingestion via **Daten**streaming" und im Glossar als "Ingestion via Streaming", bitte Einheitlich) 
- GL-0901: Kapitel 4, 6
- GL-1301: ID ist doppelt vergeben! Begriff "Modifikation" in Kapitel 4 und "Montage 4.0" in Kapitel 2. Löst diesen Doppelten-ID-Konflikt im Zuge der Verlinkung zusammen auf.
- GL-1601: Kapitel 2, 7
- GL-1800: Kapitel 2, 4, 6

**Comment by nilsBrenneis** [comment]
"GL-0404 Data Science" ist alphabetisch eingeordnet. DSGVO. ID von "DSGVO" auf 405 angepasst
